
Vagrant.configure(2) do |config|

    #Puppet 4+
    config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provision :puppet do |puppet|
       puppet.environment_path = "environments"
       puppet.environment = "vagrant"
    end
end
